# Deploy Theme to Store when new changes are pushed to master branch
name: Deploy Theme to Store

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20.16]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node }}

    - name: Install Stencil CLI Dependency
      run: npm install -g @bigcommerce/stencil-cli

    - name: Install Dependencies
      run: npm ci

#
# You must configure store credentials as secrets on your GitHub repo for automatic deployment via GitHub Actions
# This defaults to pushing the theme to channel ID 1, which is the default storefront. If you wish to push to an
# Alternate storefront, use a different channel ID
#

    - name: Connect to store and push
      run: stencil init -u ${{ secrets.STENCIL_STORE_URL_PRODUCTION }} -t ${{ secrets.STENCIL_ACCESS_TOKEN_PRODUCTION }} -pm npm -p 3000 -h https://api.bigcommerce.com

    - name: Push to store
      run: stencil push -a -d -c 1
